name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  retrofit: ^4.4.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.1.1
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.1
  test: ^1.24.0

  api_generator:
    path: ../
