name: api_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.9.1
  analyzer: ^7.3.0
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  change_case: ^2.2.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.2
  json_serializable: ^6.9.4
  lints: ^5.1.1
  test: ^1.25.15
